apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config.yaml
- jenkins-test.yaml
- pvc.yaml
- rbac.yaml
- secret.yaml
- service-account.yaml
- service.yaml
- statefullset.yaml
- test-config.yaml